apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
    trial: mihras
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
      trial: mihras
  template:
    metadata:
      labels:
        app: jenkins
        trial: mihras
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


