apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidharth
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: mihras
      containers:
        - name: app
          image: yekqpapp4q/repo:latest
          ports:
            - containerPort: 80

